### ISSUE TITLE
generateAddress counts nonce differently

### ISSUE THREAD

**Issue by frozeman** [ethereum/ethereumjs-util#4]
While trying to get a specific contract address, vital and i figured that `generateAddress` seems to count the nonce from 1, instead of 0.
```js
> eth.generateAddress('990ccf8a0de58091c028d6ff76bb235ee67c1c39',14).toString('hex')
'036a9d59dc5a1b814f8839e14a0fd9a10c6e1194'
```
Should return `d658a4b8247c14868f3c512fa5cbb6e458e4a989`.  
Using nonce 15 returns the correct address:
```js
> eth.generateAddress('990ccf8a0de58091c028d6ff76bb235ee67c1c39',15).toString('hex')
'd658a4b8247c14868f3c512fa5cbb6e458e4a989'
```

Additionally addresses with `0x` return different results. This should be the same.

**Comment by frozeman** [comment]
This was tested against pyethereum

**Comment by wanderer** [comment]
thank for reporting this @frozeman ! so two things; I assumed incrementing the nonce before you generate the address, but I see this is confusing so I will change that behavior.

On the `0x` notation. It doesn't digest them correctly because I just assume all strings are hex strings; which keeps the api simpler.

**Comment by wanderer** [comment]
ok change in version `1.5.0`      eth.generateAddress('990ccf8a0de58091c028d6ff76bb235ee67c1c39',14).toString('hex')
> 'd658a4b8247c14868f3c512fa5cbb6e458e4a989'
